### ISSUE TITLE
Add unit testing to OCPP messages

### ISSUE THREAD

**Issue by knowittobias** [AlexTelon/FlexiCharge-Backend#103]
Create unit tests that validate that OCPP messages are encoded/decoded correctly and that this process can handle illegal data in a robust way.

**Comment by fiallos00** [comment]
Validation functions has been added using https://ajv.js.org/ but no Unit Tests yet

**Comment by John-Wennerberg** [comment]
Related to issue #162 and will be implemented with that issue. Closing as not planned
