### ISSUE TITLE
Update database server version

### ISSUE THREAD

**Issue by knowittobias** [AlexTelon/FlexiCharge-Backend#119]
We are currently running an older version of postgres, 13.4. We want to stay up to date and want to update to postgres 13.7. Or if you think it is safe switch to some 14.x version.

When doing this, also make sure that you pick the most affordable option when it comes to instance size since we are still not in production and need something with good performance.

- Plan how to do this
- Test doing it on a temporary database
- Inform the other teams when you do it
- Do it smooth and quick with no problems!

**Comment by SirSitsena** [comment]
Somehow the database that is up and running has a version of 13.7 thought the "postgres-db/Dockerfile" from the main branch says 13.4. 
Planning in progress...

**Comment by Axel-RD** [comment]
Will be fixed with #127
