### ISSUE TITLE
Move .env secrets from plaintext to GitHub secrets

### ISSUE THREAD

**Issue by John-Wennerberg** [AlexTelon/FlexiCharge-Backend#173]
We need access to add and modify GitHub secrets for the Backend project.
https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions

**Comment by AlexTelon** [comment]
#172 seems related to this.

Maybe if we create an organisation, but right now I cannot find a way to give you this permission.

But I can add secrets for you for now to unblock you. I have created https://github.com/AlexTelon/FlexiCharge-Org/issues/73 to look into this.

so which secrets should I add?

```
envkey_AWS_REGION: ${{ secrets.AWS_REGION }}
envkey_USER_POOL: ${{ secrets.USER_POOL }}
envkey_USER_POOL_ID: ${{ secrets.USER_POOL_ID }}
envkey_USER_POOL_SECRET: ${{ secrets.USER_POOL_SECRET }}
envkey_ADMIN_POOL: ${{ secrets.ADMIN_POOL }}
envkey_ADMIN_POOL_ID: ${{ secrets.ADMIN_POOL_ID }}
envkey_ADMIN_POOL_SECRET: ${{ secrets.ADMIN_POOL_SECRET }}
```

Im not sure all of these need to be secrets? or just `secrets.ADMIN_POOL_SECRET`, `secrets.USER_POOL_SECRET`.

also when we have decided what should be stored as secrets and what should not I will have to request to get updated values from someone. values that have never been in git like these have.

So someone who has AWS access in the team needs to create new user and admin pool keys right and invalidate these?

**Comment by loan21xw** [comment]
The ADMIN_POOL is not even used, so I think we should create one new pool, but keep the old one for development usage. That means that everyone can use those (old) keys in their local tests as we have no local option for user pools, as we have for the database.

If we keep as much info about our user pools as possible secret, it reduces the likelihood of hacks and other attacks, even though only keeping the password secret should be enough. I think that hiding both username and passwords for services (e.g. SSH) is considered best practice.

If you only include `AWS_REGION`, `USER_POOL`, `USER_POOL_ID` and `USER_POOL_SECRET` we can set the `ADMIN` variables manually until they are removed from the code.

Please also include the username and password from https://github.com/AlexTelon/FlexiCharge-Backend/blob/main/backend-app/src/data-access-layer/db.js#L10 in secrets as `DATABASE_USERNAME` and `DATABASE_PASSWORD`.

**Comment by AlexTelon** [comment]
What's the status right now? You were able to create these yourself later right? Any action I need to take?

**Comment by loan21xw** [comment]
> What's the status right now? You were able to create these yourself later right? Any action I need to take?

I don't think so. The secrets seem to be working properly.
