### ISSUE TITLE
Create endpoint for password reset for users

### ISSUE THREAD

**Issue by knowittobias** [AlexTelon/FlexiCharge-Backend#99]
A user that forgot their password should be able to enter email address and press a button to reset the password. A link (that only can be used within 30 minutes) should be sent via email to the user. Pressing the like should make it possible for the user to pick a new password.

Use AWS SES for sending emails: https://aws.amazon.com/ses/

**Comment by FutureEngineering** [comment]
This functionality already exists but will instead of above given sequence give a verification code to the users email that they can use to change password in case they forgot. This was discussed on the Q&A 16/9 with the Project Manager and deemed to be safe enough so we move this to done.
